### PR TITLE
update jshintrc

### PR DESCRIPTION
**Pull request by diartyz**

### CODE REVIEW

**Comment by diartyz** [comment]
@juwai/frontend

**Comment by arkhi** [comment]
:+1:

**Comment by HouCoder** [comment]
:sheep:

**Comment by HouCoder** [comment]
Can some one merge this PR?

**Comment by diartyz** [comment]
i don't have write access either :disappointed:

**Comment by stuartwan** [comment]
Granted access to the @juwai/frontend team.

**Pull request merged**
