### PR TITLE
Create shared npm module with .rc files for lint tools.

### PR DESCRIPTION
**Pull request by arkhi**
The repository is a npm module.

This PR will allow the following:
1. Have a centralize repository with only .rc files.
1. It will copy or overwrite the .rc files to the folder specified by the user during the installation.
1. Until this PR is merged, you can install it in any folder with `npm install arkhi/juwai-lint-cfg`.

Copying files instead of linking them allows to fine–tune linting per project and visualize diff when updating the files in the future.

.rc files might be updated to match latest linters development in the near future, but I kept the compatibility with juwai-admin for now.

### CODE REVIEW

**Comment by HouCoder** [comment]
? Can you use `process.cwd()` as default folder if I didn't input anything?

https://nodejs.org/api/process.html#process_process_cwd

**Comment by arkhi** [comment]
@HouCoder: If I understand `process.cwd()` right, it would copy the files into the current working directory, which is the module’s directory, wouldn’t it? What would be the benefit?

Checking something else though. Thanks for the comment.

**Comment by arkhi** [comment]
@HouCoder: I updated the install script. Lots of code is gone and we don’t bother the user with the question anymore. :)

The files will be installed in the directory containing the first `node_modules`.

**Comment by diartyz** [comment]
:monkey:

**Comment by HouCoder** [comment]
:+1:

**Pull request merged**
