### PR TITLE
[JUW-1662] Update and document

### PR DESCRIPTION
**Pull request by arkhi**
- **Jira issue**: http://jira.juwai.com/browse/JUW-1662
- No testing URL: This is either in the browser or on Travis-CI.

---
- Add .stylelintrc based on juwai/juwai-com-v2#29.
- Update .jscsrc based on juwai/juwai-com-v2#23.
- Add documentation for Sublime–text.

### CODE REVIEW

**Comment by arkhi** [comment]
@HouCoder, @ben-juwai and @jonlys-juwai: Can you guys have a look when you can? Thanks!

**Comment by HouCoder** [comment]
💎 OK for me.

**Comment by jonlys-juwai** [comment]
:+1:

**Comment by arkhi** [comment]
Here we merge. Thanks!

**Pull request merged**
